version: 2.1

jobs:
  build:
    working_directory: ~/circleci-node
    docker:
      - image: "circleci/node"
    steps:
      - checkout
      - run: node main.js
  test:
    working_directory: ~/circleci-node
    docker:
      - image: "circleci/node"
    steps:
      - checkout
      - run: npm i
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
